// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5KmplFDjf7ZE',
    appId: '1:38108621:ios:f6b7dee32e274',
    messagingSenderId: '381081',
    projectId: 'astro-diploy',
    storageBucket: 'astrowayploy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_CMoAFDjf7ZE',
    appId: '1:381021:ios:f6b8fe602e32e274',
    messagingSenderId: '381086621',
    projectId: 'astrowayploy',
    storageBucket: 'astroway-dip.appspot.com',
    iosBundleId: 'com.astroypro.astrologer',
  );
}
